[package]
edition = "2021"
name    = "program"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto           = true
opt-level     = "z"
panic         = "abort"
strip         = true

[profile.dev]
panic = "abort"

[dependencies]
libc       = { default-features = false, version = "0.2.148" }